language: ruby
rvm:
- 2.1.1
env:
  global:
    secure: MulwTjUK8Rh90OfE6e7yDIrzFuFD+N2bG4o6FIiKjUEK16yJJmY93xSsH9ynFplCNhb8ZCouYySokz0do0qZbwKLL38C7GMMxrZOzqjwHqrjdjqB+1SSGR6bnqg/GCGlIyxrOg8UsFis1DOxD54ScanuP6OTyJN5Ay3gMW6KqM4=
after_success:
  - "openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
