defaults: &defaults
  mandrill_username: mandrill_username
  mandrill_api_key: mandrill_api_key
  domain: miser.example
  secret_key_base: misersecret
  email: 'no-reply@miser.co'
  api_endpoint: 'miser.example'

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
