defaults: &defaults
  sample: example

development:
  <<: *defaults
  secret_key_base: misersecret

test:
  <<: *defaults
  secret_key_base: misersecret

production:
  <<: *defaults
  secret_key_base: misersecret
